### ISSUE TITLE
make test is error 

### ISSUE THREAD

**Issue by river-lee** [xudafeng/macaca-test-sample#1]
我运行这个事例有报错，麻烦看一下什么原因？
![image](https://cloud.githubusercontent.com/assets/6419673/13870964/96d8053c-ed1b-11e5-8e12-956a25787bae.png)

**Comment by xudafeng** [comment]
@river-lee 确认 xcode 最新吗？ [参考设置](https://github.com/xudafeng/ios-simulator#usage)

**Comment by SkylineJia** [comment]
我也是这样
模拟器是9.2 的
自动打开模拟器后就停在这了<img width="317" alt="2016-03-21 10 09 22" src="https://cloud.githubusercontent.com/assets/13998564/13909412/889c63ee-ef4d-11e5-8f5c-43550537d3d0.png">

**Comment by xudafeng** [comment]
@SkylineJia 麻烦确认下 xcode 小版本

![Uploading Screen Shot 2016-03-21 at 10.20.58 AM.png…]()

**Comment by SkylineJia** [comment]
@xudafeng 一样的，我之前装过beta版Xcode，它就自动打开9.3的模拟器，之后我把beta版的Xcode卸了，会不会跟这有关

**Comment by xudafeng** [comment]
@SkylineJia 先确保你目前只有一个 xcode，然后运行 `xcrun simctl list` 看下模拟器列表有没有异常项

**Comment by SkylineJia** [comment]
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
== Runtimes ==
iOS 9.2 (9.2 - 13C75) (com.apple.CoreSimulator.SimRuntime.iOS-9-2)
tvOS 9.1 (9.1 - 13U79) (com.apple.CoreSimulator.SimRuntime.tvOS-9-1)
watchOS 2.1 (2.1 - 13S660) (com.apple.CoreSimulator.SimRuntime.watchOS-2-1)
== Devices ==
-- iOS 9.2 --
    iPhone 4s (D124542F-2647-4796-98B4-C48871C5E3C5) (Shutdown)
    iPhone 5 (D287BE7A-CB1C-45BD-8BD0-17099365B0B8) (Shutdown)
    iPhone 5s (DD23E6C7-FBC4-42E9-B21D-5A86D0E9AFFD) (Shutdown)
    iPhone 6 (0AC48DCB-C49D-4F49-B447-6A8A59C7B7CC) (Shutdown)
    iPhone 6 Plus (A1173AAD-45B7-4B9F-B86D-5474E540672A) (Shutdown)
    iPhone 6s (0118114B-6534-4095-99D2-FACB5C79E03A) (Shutdown)
    iPhone 6s Plus (BE21C4DB-5DF7-4739-900B-FF3171CCD586) (Booted)
    iPad 2 (4AC79C18-CB0F-4F13-BD4A-B018CD084F0D) (Shutdown)
    iPad Retina (4099DB7D-3904-4DE9-AE48-5F2E62D8E3C3) (Shutdown)
    iPad Air (2DBDB83D-989E-413B-9D1D-73C92148B412) (Shutdown)
    iPad Air 2 (66B60908-F6B6-4067-AE27-565B83DCF2AB) (Shutdown)
    iPad Pro (95CBF038-570F-42E3-B818-6414EEF941A8) (Shutdown)
-- tvOS 9.1 --
    Apple TV 1080p (3CB41D93-BCC8-43B0-9875-7DB3E3D02B06) (Shutdown)
-- watchOS 2.1 --
    Apple Watch - 38mm (2EAC466D-874B-44CC-B14A-5139768212A8) (Shutdown)
    Apple Watch - 42mm (A70B9B1F-9C83-42B0-B7DE-83CAAE024ABC) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-0 --
    iPhone 4s (1DD3A3DE-F708-4D90-BAB4-7A7B007E93B9) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (A5F997B5-C4A3-4410-9691-BA1E8250D2BF) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (D265F22B-BD36-4658-82BD-28015E2071E9) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (87E66C8C-811B-406C-BC10-7FA1ED44A2A3) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (0A975B42-C630-443D-907B-59A3D68CEFAA) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (1EBB3182-369C-46EF-AF71-F35F2CE224C9) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (8F559829-F472-4AEE-9A6D-903E675B84B3) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (BA37B784-533C-4D6F-A983-779774FA6628) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (60954B06-0E8A-4356-9C8B-5273890FBAD7) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (2DE5D906-2805-40F4-87B0-3A054E3DC9BF) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (2759CC54-135D-427E-AAD8-D4F911B53335) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-1 --
    iPhone 4s (CF3514EF-1E01-47CC-A5F1-2071B7DEBB62) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (AFF8E990-61FE-4E44-97B0-6DD7C32E2254) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (DBF94371-AFBF-45F8-A564-7773008A55D0) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (14FF5452-D3D7-40EC-9E4C-05AEA2DA00CE) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (F7B51AE3-7DBD-40FD-BEAF-F84416D400D6) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (BC71A35B-2B3C-4CBB-9A95-88EACC7924B8) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (78215D52-5DEC-4798-BEAC-BEF734FE9ED5) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (3D909161-5D21-4FCA-9940-2F896C67B534) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (46D9D972-EAE4-4AC3-83E6-625FCF3947E6) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (2D393DBF-4B4B-48BD-AA87-0B9A71EECF61) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (4AF1A81C-4AB4-42A4-86DE-F44ECBF2CD85) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (52CF19E0-99E2-44CA-A53B-7CF8F0ABCB83) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-3 --
    iPhone 4s (FA2361B3-FEB4-4801-B997-5B6F6BB7998E) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (0E24FBC5-CB29-4005-9561-9027FDC29B5A) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (3B830F15-15AB-484C-9296-38679BD9E90D) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (A34F11E8-29AF-4F12-B409-2A0BB029706B) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (4734DE70-3AF6-4377-A591-A404057483EE) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (7800D7EF-D7CC-403B-A647-577A74B1B3CE) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (2761F551-4801-4730-9BEF-6A1D8995C1D8) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (2AF40EEB-CE02-4113-BDC4-32AC6F08ABCE) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (12C9041B-A5B1-4FC6-AA60-4C07CED95417) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (07770A45-27BB-4928-81B8-0FED3F662E02) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (F66D996E-4047-402E-A40F-2C7AB73D2FEC) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (AE0A73E3-D100-4DF3-A3F3-DE4833BEECA6) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-0 --
    Apple TV 1080p (C1E6A4B1-3049-4D82-872C-2EF635A793B1) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-2 --
    Apple TV 1080p (3FC4C38D-DBDC-48D9-A79F-64E92D64BB5D) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-0 --
    Apple Watch - 38mm (5B9C919D-88A3-4433-B2FD-893DEC42EDE4) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 38mm (53E01841-5BC9-4D63-BB98-59D9299C02C0) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (0426120D-4AE2-4C75-A724-C27563843325) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (55A2AA5F-F4D1-4196-A9B6-024C913F0F1F) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-2 --
    Apple Watch - 38mm (CB013296-FB8C-4114-9D02-ACB4B0DFAD8F) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (86BFF208-B641-4DA2-9C6A-8332F3D229A6) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
9DDB5E86-918F-4044-82F1-51DEDD9CAC05 (disconnected)
    Watch: Apple Watch - 38mm (2EAC466D-874B-44CC-B14A-5139768212A8) (Shutdown)
    Phone: iPhone 6s (0118114B-6534-4095-99D2-FACB5C79E03A) (Shutdown)
889ECE9D-BB58-4292-8C82-DC62485FBC8A (disconnected)
    Watch: Apple Watch - 42mm (A70B9B1F-9C83-42B0-B7DE-83CAAE024ABC) (Shutdown)
    Phone: iPhone 6s Plus (BE21C4DB-5DF7-4739-900B-FF3171CCD586) (Booted)
A9FE51BC-EE5F-4AD1-863C-CFAB0292EBC5 (unavailable)
    Watch: Apple Watch - 38mm (5B9C919D-88A3-4433-B2FD-893DEC42EDE4) (Shutdown)
    Phone: iPhone 6 (87E66C8C-811B-406C-BC10-7FA1ED44A2A3) (Shutdown)
DE1A3535-C6EF-451A-90BA-4726A5CACAE7 (unavailable)
    Watch: Apple Watch - 38mm (53E01841-5BC9-4D63-BB98-59D9299C02C0) (Shutdown)
    Phone: iPhone 6s (BC71A35B-2B3C-4CBB-9A95-88EACC7924B8) (Shutdown)
5645EB93-9E67-4711-8720-34C1F444C9A0 (unavailable)
    Watch: Apple Watch - 42mm (0426120D-4AE2-4C75-A724-C27563843325) (Shutdown)
    Phone: iPhone 6 Plus (0A975B42-C630-443D-907B-59A3D68CEFAA) (Shutdown)
17CD8849-DEB9-4950-8776-C3B7A8B69F76 (unavailable)
    Watch: Apple Watch - 42mm (55A2AA5F-F4D1-4196-A9B6-024C913F0F1F) (Shutdown)
    Phone: iPhone 6s Plus (78215D52-5DEC-4798-BEAC-BEF734FE9ED5) (Shutdown)
3858695E-FC21-4CA4-84AC-4ACF2E11A0D6 (unavailable)
    Watch: Apple Watch - 38mm (CB013296-FB8C-4114-9D02-ACB4B0DFAD8F) (Shutdown)
    Phone: iPhone 6s (7800D7EF-D7CC-403B-A647-577A74B1B3CE) (Shutdown)
7A3915B3-43F0-4C77-BCFD-181A04204674 (unavailable)
    Watch: Apple Watch - 42mm (86BFF208-B641-4DA2-9C6A-8332F3D229A6) (Shutdown)
    Phone: iPhone 6s Plus (2761F551-4801-4730-9BEF-6A1D8995C1D8) (Shutdown)


现在打开的是iPhone 6s Plus模拟器

**Comment by river-lee** [comment]
![Uploading image.png…]()

xcrun simctl list 没有发现什么异常项目

== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
== Runtimes ==
iOS 9.2 (9.2 - 13C75) (com.apple.CoreSimulator.SimRuntime.iOS-9-2)
tvOS 9.1 (9.1 - 13U79) (com.apple.CoreSimulator.SimRuntime.tvOS-9-1)
watchOS 2.1 (2.1 - 13S660) (com.apple.CoreSimulator.SimRuntime.watchOS-2-1)
== Devices ==
-- iOS 9.2 --
    iPhone 4s (7748C92C-7608-48D2-BBCD-DB64E71C8045) (Shutdown)
    iPhone 5 (3F0A978F-5D03-4626-9D10-7255F1D7747A) (Shutdown)
    iPhone 5s (453E0880-BBDF-4C7F-A660-CB578BB63EAE) (Shutdown)
    iPhone 6 (902679C8-B949-4B59-914E-B13ED45DC4FB) (Shutdown)
    iPhone 6 Plus (E5D65E2F-385C-4B6E-A05F-F0BA4C0D70B9) (Shutdown)
    iPhone 6s (04365366-6B25-42C1-9FF5-88815338DF98) (Shutdown)
    iPhone 6s Plus (BC1B7560-54C8-4718-A965-9D4D694B26A8) (Shutdown)
    iPad 2 (ADF81491-5765-4D18-A04D-EE3173C6A2CD) (Shutdown)
    iPad Retina (24D1ECC9-2E92-4E5A-A6B6-74433621582B) (Shutdown)
    iPad Air (F7ED3987-8189-44CA-83FE-9DA74E3C77BE) (Shutdown)
    iPad Air 2 (28C0EEBD-F6A1-456F-9AE1-BED5AC754797) (Shutdown)
    iPad Pro (2FBE80DE-FCB3-4D4C-802C-36F8546F1EDC) (Shutdown)
-- tvOS 9.1 --
    Apple TV 1080p (9D89503C-BBA2-4F80-B199-9F86B027D215) (Shutdown)
-- watchOS 2.1 --
    Apple Watch - 38mm (FC68AD5D-21EB-45D4-BC36-F87A82033CEE) (Shutdown)
    Apple Watch - 42mm (2CC117B6-B14A-47C9-835D-826BC7C2DD93) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-1 --
    iPhone 4s (6F28F958-85F1-4F1A-B143-7AB91670FD49) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (30CB0867-8AA0-420E-91CF-D01F4601F8F6) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (8AD512F5-724C-4BC0-BB35-9F93A445E692) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (24BCD420-9EF1-4E45-B105-64F70FE7EB47) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (2841E95E-DD6D-4D21-B2A9-5EC434BF5FCB) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (65EB054A-8301-47E1-8C54-976C65E02923) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (9F0AE774-29D6-4077-90F9-08D3B079117C) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (DCA57742-1C7F-46BA-986D-834E090D89AE) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (0FB73A37-553C-48DC-ABCC-B9485B4DDD38) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (80D2E869-DAFB-4B99-A3B2-C915F72A82F5) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (CA0E6C59-CE90-437A-BAFE-49B2B1D30640) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11FF31C1-5CD8-43F0-8DE2-A3347B644508) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-0 --
    Apple TV 1080p (20577E75-546A-4310-8F9C-AC2E239432C1) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-0 --
    Apple Watch - 38mm (200E4A84-5E30-4100-8ABD-76C2E4254DBA) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (7C330B15-57B1-4BBA-BC57-9EA4A44D7ABA) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
6EC36F4B-4D4A-46A2-88B4-BC2B2A3339D1 (disconnected)
    Watch: Apple Watch - 38mm (FC68AD5D-21EB-45D4-BC36-F87A82033CEE) (Shutdown)
    Phone: iPhone 6s (04365366-6B25-42C1-9FF5-88815338DF98) (Shutdown)
171585F2-6620-4445-8B93-152256CFCDC8 (disconnected)
    Watch: Apple Watch - 42mm (2CC117B6-B14A-47C9-835D-826BC7C2DD93) (Shutdown)
    Phone: iPhone 6s Plus (BC1B7560-54C8-4718-A965-9D4D694B26A8) (Shutdown)
7E398C98-F458-4F35-A388-2BCA72F4A197 (unavailable)
    Watch: Apple Watch - 38mm (200E4A84-5E30-4100-8ABD-76C2E4254DBA) (Shutdown)
    Phone: iPhone 6s (65EB054A-8301-47E1-8C54-976C65E02923) (Shutdown)
CDB784F4-71AF-4025-AEF3-C278CBDD7E79 (unavailable)
    Watch: Apple Watch - 42mm (7C330B15-57B1-4BBA-BC57-9EA4A44D7ABA) (Shutdown)
    Phone: iPhone 6s Plus (9F0AE774-29D6-4077-90F9-08D3B079117C) (Shutdown)

**Comment by xudafeng** [comment]
@river-lee @SkylineJia 开发者模式有没有开启？

```
$ sudo /usr/sbin/DevToolsSecurity –enable
```

**Comment by SkylineJia** [comment]
有

**Comment by river-lee** [comment]
启动了，还是不行的

**Comment by xudafeng** [comment]
```
$ make test
```

之后，只启动了3456端口吗？这里的log请贴一下

**Comment by river-lee** [comment]
sudo make test 
macaca run --server --verbose
>> index.js:62:12 [master] pid:8425 webdriver server start with config:
 { port: 3456,
  ip: '192.168.108.81',
  host: 'river.local',
  loaded_time: '2016-03-21 10:47:41' }
>> middlewares.js:31:10 [master] pid:8425 base middlewares attached
>> router.js:97:10 [master] pid:8425 router set
>> webdriver sdk launched
>> 
>> 
>>   macaca test sample
>> responseHandler.js:24:12 [master] pid:8425 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"IOS","platformVersion":"9.2","deviceName":"iPhone 6","app":"/Users/river/webProjects/macaca-test-sample/app/ios-app-bootstrap.zip"}}
>> session.js:22:10 [master] pid:8425 Creating session, sessionId: cb5e5486-5a9a-4210-be75-658400312270.
>> helper.js:202:12 [master] pid:8425 Unzipping local app form /Users/river/webProjects/macaca-test-sample/app/ios-app-bootstrap.zip
Get bundleId xudafeng.ios-app-bootstrap from plist /tmp/ios-app-bootstrap.app/Info.plist
>> macaca-ios.js:128:10 [master] pid:8425 Get available devices [{"name":"iPhone 4s","udid":"7E23DFB9-C74E-4DF7-968B-B332FD1C47CC","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5","udid":"5F9861BD-F64C-415E-904A-DE091D3AC984","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5s","udid":"5C52F8F1-9C5C-4CA6-A801-1AC28152559A","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6","udid":"1CCBA7EF-7B6D-4BF8-93B5-558CF14487DA","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6 Plus","udid":"CAE1B56D-DA84-46BC-BF55-65C7725EECC5","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s","udid":"97E9BF66-7569-4474-A471-6965F7B31639","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s Plus","udid":"B7618CDE-52B3-450F-BAD3-D026940A01B3","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad 2","udid":"82A41854-8B52-414B-8EC7-886C5DA1544E","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Retina","udid":"81A0696F-F959-4EF9-B753-AF5C03CD8901","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air","udid":"8F1266BC-42D5-4C28-958B-38AA81C6CD99","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air 2","udid":"14AF56E5-BB99-4AA7-AF79-367147FECFDE","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Pro","udid":"CCB00F4E-1601-46E4-BDD3-E743783A24FC","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"Apple TV 1080p","udid":"D749C2AD-DCF0-424C-9B27-624CCDFC9A3C","state":"Shutdown","available":true,"runtime":"tvOS 9.1"},{"name":"Apple Watch - 38mm","udid":"9C0502EB-8402-4F1C-8062-665B6E12E4EA","state":"Shutdown","available":true,"runtime":"watchOS 2.1"},{"name":"Apple Watch - 42mm","udid":"8C52CC40-3903-4D0C-AF7D-FF85528FC5FB","state":"Shutdown","available":true,"runtime":"watchOS 2.1"}]
>> macaca-ios.js:94:12 [master] pid:8425 Kill simulator failed Error: Command failed: /bin/sh -c killAll Simulator
No matching processes were found

>> macaca-ios.js:100:12 [master] pid:8425 Shutdown simulator B7618CDE-52B3-450F-BAD3-D026940A01B3 failed Error: Command failed: /bin/sh -c xcrun simctl shutdown "B7618CDE-52B3-450F-BAD3-D026940A01B3"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to shutdown device in current state: Shutdown

**Comment by xudafeng** [comment]
@river-lee 没问题的，不过make test 不用sudo吧

**Comment by river-lee** [comment]
不然写入日志没有权限 所以就干脆用sudo了；
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/logs/digest-2016_03_21.log'
    at Error (native)

问题应该跟这个无关吧

**Comment by xudafeng** [comment]
忘了说sudo的问题了。。。

**Comment by river-lee** [comment]
ok 可以啦，果然是sudo的问题。

**Comment by xudafeng** [comment]
@river-lee 我记录到文章里，免得更多人遇到麻烦

**Comment by river-lee** [comment]
对于这样的工具文档确实不全，我之前找到这个工具尝试了很久最后在你的一个博客上找到怎么使用，你的官方文档连之前的demo的地址都没有。希望你能够将官方地址文档全面一些。

对于这样工具开发和学习需要具备哪些技能？原生开发也需要是吧？

**Comment by xudafeng** [comment]
@river-lee Guide 在抓紧准备

macacajs/macaca#8

不需掌握原生开发，但是需要花一段时间实践移动 UI 测试

**Comment by SkylineJia** [comment]
@xudafeng 加油，维护开源工具挺不容易的。

**Comment by xudafeng** [comment]
请查看[文档](http://macacajs.github.io/macaca/guide.html#/environment-setup)
